import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";

const fontPage = Fredoka({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${fontPage.className}`}
      >
        {children}
      </body>
    </html>
  );
}
