import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { GlobalProvider } from "@/context/GlobalContext";
import { Modal } from "@/components/Modal";
import { Order } from "@/components/Order";

const fontPage = Fredoka({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TastNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${fontPage.className}`}
      >
        <GlobalProvider>
          <Navbar />
          <div className="overflow-hidden w-full relative">
            <Order />
          </div>
          {children}
          <Modal />

        </GlobalProvider>
      </body>
    </html>
  );
}
